### ISSUE TITLE
Stuck after game end

### ISSUE THREAD

**Issue by Rolwinkle** [Cryptix808/BattleShip#1]
Description:
Clicking outside of the box asking if you want to play again leaves you hanging with nothing to do.

How to reproduce:
1. Finish a game
2. When the game asks if you want to play again, click outside of the box
3. "Play again" window closes, leaving you without an escape.

Severity: Minor.  The game functions well, it just does not always allow the player enough time to realize they have won and they click outside of the box, not allowing them to play again if they wanted to.

**Comment by NateKliner** [comment]
Duplicate ticket, closing

**Comment by Rolwinkle** [comment]
Issue still pertains.
