### ISSUE TITLE
placing some pieces is rejected but no error is told - minor 

### ISSUE THREAD

**Issue by hendersj22** [Cryptix808/BattleShip#10]
When I try to put a piece it is rejected for a reason I think because not enough space, but there is no error notice. 

GUI - minor 

If you place a ship but its not enough space it is rejected, however its not always clear why. If there was feedback that would help. 

To replicate this try putting ships in a different spaces until it is rejected and you will see it.

**Comment by NateKliner** [comment]
Duplicate ticket, closing.

**Comment by hendersj22** [comment]
Fixed
