### ISSUE TITLE
Game crashes when it’s human vs. wifi player, instead of throwing out an error /Improvement

### ISSUE THREAD

**Issue by Gmunster33** [Cryptix808/BattleShip#15]
What can be improved is there should be an exception to this case so that the game will not crash, but instead print out an error stating that the player is not allowed to play the game without linking up with another player through the network.
To replicate this bug, select one human and one wifi player in the main menu, and attempt to play the game.

**Comment by NateKliner** [comment]
This is just an enhancement. As we all know, the wifi player is pretty much impossible to test if it is working now considering the circumstances, so we will not be addressing this and focusing on other issues. Closing.
