### ISSUE TITLE
Computer places boats in same spot

### ISSUE THREAD

**Issue by hendersj22** [Cryptix808/BattleShip#17]
When you beat the computer and then restart when offered to play again the computer places its boats in the exact same spot. This is a bug because then you already know where to attack

**Comment by NateKliner** [comment]
Would this repeat itself every time? We only have 20 boards so you mightve gotten the 5% chance to get the same board.

**Comment by hendersj22** [comment]
Yup looks like that was the case. Sorry for the mistake on my part
