### ISSUE TITLE
Swapping AI and Human Players in config makes game unplayable

### ISSUE THREAD

**Issue by zmader** [Cryptix808/BattleShip#5]
Bug- Swapping AI and Human Players in config makes game unplayable
Critical Bug - game is unplayable
To reproduce, swap the human and AI player on startup, and run the game. This makes it impossible to place boats on the board or interact with any other elements of the GUI. This bug is critical because if the game is operated in this manner, the game cannot be played. This might be an issue with hard coding values for AI and human players, so swapping them causes issues with interaction.

**Comment by NateKliner** [comment]
Duplicate ticket, closing

**Comment by Rolwinkle** [comment]
Issue still pertains. Cannot place ships on the board to start the game.
