### ISSUE TITLE
GUI in setup phase sometimes unresponsive -- Minor

### ISSUE THREAD

**Issue by malikh22** [Cryptix808/BattleShip#7]
Component: GUI

Problem: If you place a ship and try to move it a square or two up in its current column, the GUI occasionally does not move it to that new position, even if it is legal. However, it moves just fine from column to column. This is minor because the game can still be played, but it makes it a little bit more frustrating.

Steps to recreate:
1- start a game with dumb AI
2- select the largest boat 
3- place it on the board
4- try to shift it one square above in the same column
5- most often, the ship will not move to the new square, even if it can fit

**Comment by NateKliner** [comment]
Does not hinder gameplay, only a minor inconvenience. I will be closing this because it was not as significant of an issue as others.

**Comment by malikh22** [comment]
Given above comment, consider fixed.
