### ISSUE TITLE
Can only see enemy's hits on player-- Major

### ISSUE THREAD

**Issue by malikh22** [Cryptix808/BattleShip#8]
Component: GUI

Problem: The GUI does not give indications of enemy moves if they are misses. This makes it difficult for the player to know if it is their turn or not. Also, based on the rules of Battleship, these misses should also be visible (even if in this case, it's just the player who needs to see). This is a major issue because it is hard for the player to know if the AI has moved yet when playing against an AI. 

Steps to recreate:
1- start a game against the dumb AI
2- place your boats
3- confirm your placements
4- make a move
5- if the opponent has missed, you won't see anything change on your board. However, it is now your turn.

**Comment by NateKliner** [comment]
Would this be less of an issue of I had a turn indicator?

**Comment by malikh22** [comment]
That could definitely be helpful

**Comment by NateKliner** [comment]
Duplicate ticket, closing

**Comment by malikh22** [comment]
Fixed-- the new hit/miss counter is helpful and allows for this not to be an issue.
