### ISSUE TITLE
Dialogue box on game end vanishes if you click too fast - minor

### ISSUE THREAD

**Issue by hendersj22** [Cryptix808/BattleShip#9]
When I spam clicked the box saying who won disappeared before I could read it. 

GUI - minor 

I think this is an issue because I didn't have time to read it because I was clicking the screen to place a new attack not realizing I had won. Maybe if I knew I was down to the last ship I would have been more careful but it wasn't clear I was almost done. 

To replicate this just win the game but click the screen really fast to continue attacking and when you win the box will appear but vanish right away.

**Comment by NateKliner** [comment]
Not a significant issue to our game. Closing.

**Comment by hendersj22** [comment]
Fixed
